---
deployment:
  tasks:
    - export DEPLOYPATH=/var/www/u2208459/public_html/portal02-test.ru
    - /bin/cp index.html $DEPLOYPATH
    - /bin/cp style.css $DEPLOYPATH
    - /bin/cp -R portal $DEPLOYPATH